/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCivilianRouteImport } from './routes/_authenticated/civilian'
import { Route as AuthenticatedAuthorityRouteImport } from './routes/_authenticated/authority'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCivilianRoute = AuthenticatedCivilianRouteImport.update({
  id: '/civilian',
  path: '/civilian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorityRoute = AuthenticatedAuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/authority': typeof AuthenticatedAuthorityRoute
  '/civilian': typeof AuthenticatedCivilianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/agency': typeof AuthenticatedAgencyRoute
  '/authority': typeof AuthenticatedAuthorityRoute
  '/civilian': typeof AuthenticatedCivilianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRoute
  '/_authenticated/authority': typeof AuthenticatedAuthorityRoute
  '/_authenticated/civilian': typeof AuthenticatedCivilianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/agency' | '/authority' | '/civilian'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/agency' | '/authority' | '/civilian'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/agency'
    | '/_authenticated/authority'
    | '/_authenticated/civilian'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/civilian': {
      id: '/_authenticated/civilian'
      path: '/civilian'
      fullPath: '/civilian'
      preLoaderRoute: typeof AuthenticatedCivilianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authority': {
      id: '/_authenticated/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthenticatedAuthorityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRoute
  AuthenticatedAuthorityRoute: typeof AuthenticatedAuthorityRoute
  AuthenticatedCivilianRoute: typeof AuthenticatedCivilianRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRoute,
  AuthenticatedAuthorityRoute: AuthenticatedAuthorityRoute,
  AuthenticatedCivilianRoute: AuthenticatedCivilianRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
